// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// minimizR
Rcpp::List minimizR(Rcpp::NumericVector start, Rcpp::Function objective, Rcpp::Function gradient, Rcpp::Nullable<Rcpp::List> control);
RcppExport SEXP _minimizR_minimizR(SEXP startSEXP, SEXP objectiveSEXP, SEXP gradientSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type objective(objectiveSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(minimizR(start, objective, gradient, control));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_minimizR_minimizR", (DL_FUNC) &_minimizR_minimizR, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_minimizR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
